# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_userfeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
